name: get_rx_persist
description: Get Rx Lite-weight Persist, which enable auto persistence feature to get_rx package
version: 1.1.0+1
homepage: https://github.com/rua-flutter/get_rx_persist

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ">=5.0.0-release-candidate-4 <6.0.0"
  get_storage: ">=2.0.0 <3.0.0"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
